//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exrate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public Bank()
        {
            this.Address = new HashSet<Address>();
            this.Rate = new HashSet<Rate>();
        }
    
        public string ShortName { get; set; }
        public string Name { get; set; }
        public string Logo_small { get; set; }
        public string Logo_big { get; set; }
        public string Website { get; set; }
        public string CitiesIds { get; set; }
    
        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<Rate> Rate { get; set; }
    }
}
