//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exrate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Address = new HashSet<Address>();
            this.Rate = new HashSet<Rate>();
        }
    
        public int Id { get; set; }
        public string NameENG { get; set; }
        public string NameRUS { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public int UTCOffset { get; set; }
        public int MapZoom { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<Rate> Rate { get; set; }
    }
}
